# AI Agent Orchestration System - Google Hackathon
# Docker Compose for Professional Demo

version: '3.8'

services:
  ai-agent-demo:
    build: .
    container_name: ai-agent-orchestration-demo
    ports:
      - "7860:7860"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-demo_mode}
      - PYTHONPATH=/app/src
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./memory_data:/app/memory_data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-agent-demo.rule=Host(`localhost`)"
      - "traefik.http.services.ai-agent-demo.loadbalancer.server.port=7860"