# CI Workflow for Jeannine_Jordan Google Hackathon Submission
# Validates AI Agent Orchestration System functionality

name: AI Agent Orchestration CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run smoke tests
      run: |
        chmod +x TEST.sh
        ./TEST.sh
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    
    - name: Test Docker build
      run: |
        docker build -t jeannine-jordan-test .
    
    - name: Test Docker smoke test
      run: |
        docker run --rm jeannine-jordan-test ./TEST.sh